import sys
readl = sys.stdin.readline

n = int(readl().strip())
lst = [list(map(str, readl().strip())) for _ in range(n)]
ans = n*n
def reverseCoin(c):
    if c == 'H':
        c = 'T'
    else:
        c = 'H'
    return c

ans = n*n

for i in range( 1 << n ):
    sum = 0
    for c in range(n):
        nowT = 0
        for r in range(n):
            state = lst[r][c]
            if ((1 << r) & i):
                if state == 'T':
                    state = 'H'
                else:
                    state = 'T'
            if state == 'T':
                nowT += 1
        sum += min(nowT, n - nowT)
    ans = min(ans, sum)
print(ans)


''' 너무 느림
for i in range(1 << n):
    sum = 0
    for j in range(n):
        t = 0
        for k in range(n):
            cur = lst[k][j]
            if (i & (1 << k)) != 0:
                cur = reverseCoin(cur)
            if cur == 'T':
                t += 1
        sum += min(t, n-t)
    if sum < ans:
        ans = sum
print(ans)
'''
'''
for m in range(n):
    for i in range(n):
        lst[m][i] = reverseCoin(lst[m][i])
        countup()
        lst[i][m] = reverseCoin(lst[i][m])
        countup()
'''
'''
17
THHTHHHHHTTTTTTTH
THTHHTHHTHHTTHTHT
HTTTHTTHTTHTTTHTH
HTTTTTTHHTHHHHHHH
HHTHTHHHTTHTTHHHH
HHTHHTHTTHHHTTTTT
HHHTHTHTTHHHTTTTH
HHTHTTTHTHHHTHHHT
TTTTTTTTTTHTHHHHH
THHTHTHTHTHTTTHHT
HHHHTHTHHTHTTHHHH
TTHTHTTTHTTHTHTTH
TTHHTHHHTTHTTTTTT
HTHHHHHHHTTHTTHHH
HHTHTHTTHHTHHHTHH
HHTTTHHHTHHTTTTHH
TTHHHTTTHTTTTHTHT
93

19
HTTHHTHTTHTHHTTHTTH
THHTTTTHTTTTHTTTTHH
THHTHHTHTHTTTTTHHHT
THTHHHTHHHTTTHTHHTH
TTHHHTTHTHHHHTTHTHT
THHHHHHTTHTTHTTHTHH
THHTTHTTTTHTHTTTHTT
TTHHHHHHTHTHHHTTTHH
TTHHHTHTTHHHHTHHTTH
HHTHHTHHHTHTHTTHHTH
HTTTHTTTHTHHHTHTTTT
HHHHHHTTTTTHHHHTHTH
THTHHTTTHHTTHTHTHTT
THHHTHTHTHTHHHTTHHH
THTTTTTHHTHTHTTTTTT
THHTTHHHHHTTHTTTTTT
HTHTHHTTTTTTHHHTTHH
TTTHTHHTHTHHTHTTTTH
HTTHHHTHTHTTHHHTHHT
120

20
THHTHTTHTTHTHHHTTHTH
TTTTHHTTHTTTTTHTHTTT
TTHHTHTHHTHTHHHTTHTT
THTHTTHHHTTTHHHHTTTT
HHTHHTHTTTHHHTHTTTHT
HTHHHTTHHHTHTTTTTHTT
THTTHTTTTTTHHHHTHHHH
HTTHHHTHTTHTHTTHHTTT
HHTHHTTTTTHHTHHTTHHH
HHHTTHTHHTTTHHTHHHHH
HHTTTHTTTTHHHHHTTHHH
HTHTHTHHHTTTHHHHHHTT
HTHTTHTTHHTHHHTTTHTH
TTTTTHHTTHTHHTHTHHTT
TTTTTHHTHTTTTHTHHHHT
HHHHTTTTTHHTHTHHTTHT
HTTHHHHTTHTTTTTHTHTH
HTTHHHTTHTHTTHHHHHTT
HHHTHTHTTHTHTTHTTHHH
HTTTHHHHTHHHTHHHTHHT
137

8
THTHHHTH
TTHTHHTH
HHHTHHHH
TTTHHTHH
HHHTHHHH
TTHTHTHT
HTHHTTHT
HHHTHTTH
15

17
HHHHHHTHTTTTTTHHH
THTHTHTTHTHTTHTHT
HTHHHTTTTTHTTHHHH
TTHTHHHHHHTHHTTTT
TTTTTHHTTHHTHTHTT
TTHHHTHHHHHTHHHTT
HHHHTHHHTHTTTTTHH
THTHHTHHHTHTHTTHH
HTHTHHHTHTHHHTTTH
THTHTHHHHTHHHTHHT
TTHTHHTHTHTHTTHTT
HTHTHTTTTHHTHTHHT
TTTTTHHHHTHTTHHHT
HTTTTTTTHHHHHTHHT
HTHTHHHHHHTHTTTHT
THHHHTTHTHTTTTHHT
HHHHHTHHTHTTHHHHT
94

20
HHHTHTHHTTTTTTHHHTTH
TTHHHTTHHTHHTTTTHHTH
THHHTTTHTTHHTHTTTTTH
THHHHHTHTTTHHHHTHTTH
THHHTTTHHTTHHHTHTHHH
THTHHHHTHHTHHTHTTHTT
THHHHTHTHTTTTHHTTHTT
HHTTHHTTTHHTHHHTTTHH
TTHHTTTTTHHHTTHHTTHH
TTTTTHHHHTTTHTTHTTTH
HTHHTHHHTTTTTTHTTHHH
TTHHHTHHHTTHTTTHTTHH
THTTTTHHTHHTHHTHTTHT
HTHHHHTTTTTHTTTTHHTT
TTHTTHTTHHTTHTTHHTHT
THTHHHHTHHTHHTHTHTHT
THHHHHTHHTTHTHHTTTTH
HTTTHHTHTHTHTHTTTTHT
HHHTHHTHHTTTTTHTTTTT
HTTTHHTTTHTHHHTTHHHT
133

9
HTHTHHTTT
TTTHTTHHT
HHTTTHTHH
HTHTHTHHH
THHHHHHTH
HHTTHTHHT
THTHTHTHT
THHTHTHTH
HHHHTHHHT
23

15
TTTHTTTTTTHTTTT
HTTHHHHTTHHTHTT
HTHHTHTHHHTTTHT
TTHTHHTTHTHTTTH
HTTTTTTHTTHTTHH
HHTHHTTHHTTTHTT
TTTTTTHTTHHTTTT
HTHHHHTTHHHTHHT
THHTHTTHHHTTTHH
THTTTTHHHTHHHTT
HTHHHTHTTHHTTTT
HTHTHTTTTHTHTTH
HHTTHHTHHTTTHHH
TTTHTTTTTTTHTTT
HHTTTTTHHHHTTHT
71

9
THTTHTHTT
HTTTHHHHT
HHTHHTTHT
HTHHHHTTT
TTTHTTHTT
THTHTHHHT
HTTHTTHTT
HTTHTHTHT
TTTHTHHHT
22

13
TTHTHTHTTHHTH
THHTHTHHHHTTH
THHTHHHTTTTTH
THHTTTHHTHTHT
HHTHHHTHTTHTH
TTTTHHTHTTTHH
THHHHTHTHTHHH
HTHHTTTTHHHHH
HTTHHTTHHTTTT
HTTTHHTTHHHHT
THTHHTTHTTHTT
THHTHTTHHTTTT
HTHTHTTTTHTTT
53

16
TTTHHTTTTTTTHTHH
HTHTHHTHHHHTTHTT
HTHHHHHTTTHHHTTT
HTHTTHTHTTTTHTHH
THTHTTTTTTHTHTTT
THTHTTHTHHTHTHHT
HTHTHHTTHTHTHHTH
TTTHHHTHTTHHHHHT
THTTTTTHHHTTHHTH
HTHHTHHTHTTTHTHT
THTTHTTHHTTHHHHT
HTTHTHTHTHTHTHTT
HTTTTHTTHTTHTHHT
HHTHHTTTHTHHTHHT
HTHTTTHTHTHHHTHH
TTTHHTTHTHTTTTTH
85

9
THTTTTHTT
HHTTTHTHH
HHTTHHHTH
THTTHHTTH
TTTTHHHHT
TTHHHHHHT
HTHHTHTTH
HHHHTHHHT
HHHHHTTHH
23

18
HHTHHHTHHHTTHTTHHT
HHHTHTHTTTTHTHTHTT
THHHTTHTTTHTHTHTHT
HHHTTHTTHHTTTTTHTT
HHTHTHTHTHTTHHTTHT
HTTTHTHHHTHHTHTTTT
HTTHTTHHHHHTHTTHTH
HHHTTTHHHTTHTTHTTH
HHTHHTHHHHTHTHHHTH
TTTTTTHHHTTHHHHTHT
HHHTTHTHTHTTTTHHTT
HTTTHTTHTHTTTTTTHT
TTHHTTTHHTTTTHHTTT
HTTTTTHHHTHHTHHHTT
HHHHTTTTTTHHHTHHTH
THHHHHTHTTHTTTHHTT
HTTHHHHHHTTTHTTHTH
TTTTHTTHTTTHTHHTHH
105

13
TTTHHTHTHHTHT
HHHHTHTHHHTTH
TTTTTHTTHTHTH
HHTHTTTHHTTTH
HHHHHHTHTTTTH
TTTTHHTTTTHTH
TTHHTTHHHHHHT
THHHHTTHTHHHH
HTTTHHTTHHHHH
TTTTHTHTTHTHH
TTTHTTTHTHTHH
TTHTTHHTTTTHH
HHTTTTTTTHHTH
52

14
THHHTTHTHHHHHT
HTHTTTTHTTTTHT
THHTHTHHHHTTHT
THHTTHHHTTTHHT
HTHTHHTTHHTTTT
HTHHHTTHTTTHHT
HTHHHTHTHTHTHH
TTTHHHHTTHTTHT
TTHTTTHTTTHHHT
THTTTTTTTTTHHH
HHHHTTHTHHTHHT
HTTHHTTTTHTHTT
THTTHTTHHHHHTH
HHHHTTHHHTTHTT
61

13
TTHTTTHTTHHHH
THTTHHTHTHTTT
THHHTTTTHHHTH
THTHHTTHTTHTH
THTHTTHHTHTHT
THHHTHHTHTTTH
HTHTHHTTHHTTT
HTTHTTHHHTTTH
HHHTTTHHTHHTH
HHHTHHTTHHTHT
TTTTTHHHHTTHH
THHHHHHTHHTHT
TTHTHHHTTTTTT
52

17
HHTTHTTTHHTTHTTTH
HTTTHTTHTHHTHTHHH
TTTHHTTTHTHHTTTTT
HHTTHHHHTHTHTTTTH
HHTHHHTTTTTHHTTHH
HHTTHHHHHHTTHTHHH
TTHHTTHTTTHTTHHTT
HHTHTHHHHTHTHTTTT
HTHHTTHTHTTHTTHTT
HHTTHHHTHTHHHTHTT
THTTHHTTHHHTHTTHH
HHHTHHHHTHTHHHTHT
HTHHHTHTHTHTTHHHH
THTTHHHHTHTHHHHTH
HTTHHHTHHHHTHHTHT
TTHHHTHTTHTTTTTTH
THTTHTHHTTHHHTHHT
86

12
TTTTTTHHHHTT
TTTTTHHHHTTH
TTHTTHTHTHTT
HHTTTHHTTHHH
HTHHHHTTTTHT
HHHHHHTHHHHH
TTHTTTTTTHTH
THHTTHHTHHTH
TTHTHTHTHTHT
HHTTTHHHHHHH
HTHHTHTHHTHH
HHHHHTHHHHTT
44

6
HHTTHH
TTHHTH
TTTHTH
HTTTTT
TTTHHT
TTHTTT
9

10
HTTTHHTHHH
TTTHHHHHTH
THHTHHHHHT
HHHHHTTTTT
THHTTHTHTT
THTHHTTTTH
HHHHTTTTTT
HHTTTHTTHT
THHTHHHHTT
HTHHTTHTTT
26
'''
